#!/bin/bash
#PBS -N Filter_summary
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=30
#PBS -l mem=150gb
#PBS -l walltime=48:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Load the R module"
module load software/R_3.6.2

echo "---------------------------------------"
echo "Execute R script to get summary of different filters"
source /usr/local/miniconda3/etc/profile.d/conda.sh
conda activate R_3.6.2
Rscript /home/jwestaway/pk_pipeline/ZB_100/scripts/14_Consensus_vcf/filtering_test/filter_comparison.R
conda deactivate

echo "---------------------------------------"
echo "Finished"