#!/bin/bash
#PBS -N Calc_snps_&_indels
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=11
#PBS -l mem=50gb
#PBS -l walltime=12:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to bcftools"
export PATH=$PATH:/home/jwestaway/pk_pipeline/tools/bcftools-1.13/
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus

echo "---------------------------------------"
echo "SNPs"
bcftools view -v snps PK_consensus_corrected.vcf > PK_consensus_corrected_snps.vcf

echo "---------------------------------------"
echo "Indels"
bcftools view -v indels PK_consensus_corrected.vcf > PK_consensus_corrected_indels.vcf

echo "---------------------------------------"
echo "Finsihed"
