#!/bin/bash
#PBS -N Indel_Realign_ZB_Test
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=10
#PBS -l mem=50gb
#PBS -l walltime=12:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to samtools"
export PATH=$PATH:/usr/local/jdk1.8.0_131/bin
export PATH=$PATH:/usr/local/jre1.8.0_111/bin
export PATH=$PATH:/usr/local/GenomeAnalysisTK-3.2.2 
export PATH=$PATH:/usr/local/miniconda3/envs/assembly/bin/

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
INDIR="/home/jwestaway/pk_pipeline/ZB_100/outputs/direct_alignment/"
OUTDIR="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/GATK/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4"
PICARD="/usr/local/miniconda3/pkgs/picard-2.21.9-0/share/picard-2.21.9-0/picard.jar"
INDEXTDIR="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
INTERVALS="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/strain_A1_H.1.Icor.fasta.bed"
KNOWNSITES="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/PK_consensus.vcf"


mkdir $OUTDIR
 
echo "---------------------------------------"
echo 'Sort and Index bam files'
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/direct_alignment

samtools sort -@ 10 PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.bam > PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.sorted.bam

samtools index -@ 10 PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.sorted.bam

echo "---------------------------------------"
echo 'MarkDuplicates'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -jar $PICARD \
    MarkDuplicates AS=TRUE VALIDATION_STRINGENCY=LENIENT \
    I=$INDIR/SAMPLE.sorted.bam \
    O=$OUTDIR/SAMPLE.dupmarked.bam \
    M=$OUTDIR/SAMPLE_picard_metrics_file.txt 

echo "---------------------------------------"
echo 'Change header @RG and index' 
samtools view -H $OUTDIR/SAMPLE.dupmarked.bam | \
    sed 's,^@RG.*,@RG\tID:SAMPLE\tSM:SAMPLE\tLB:None\tPL:Illumina,g' |  \
    samtools reheader - $OUTDIR/SAMPLE.dupmarked.bam > $OUTDIR/SAMPLE.dupmarked.reheader.bam

samtools index $OUTDIR/SAMPLE.dupmarked.reheader.bam 

echo "---------------------------------------"
echo 'RealignerTargetCreator'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS  -Xms3200m -Xmx3600m -jar /usr/local/GenomeAnalysisTK-3.2.2/GenomeAnalysisTK.jar \
    -T RealignerTargetCreator \
    -nt 10 \
    -R $INDEXTDIR \
    -I $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.reheader.bam \
    --intervals $INTERVALS \
    -known $KNOWNSITES \
    -o $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigner.intervals
    
echo "---------------------------------------"
echo 'IndelRealigner' 

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS  -Xms3200m -Xmx3600m -jar /usr/local/GenomeAnalysisTK-3.2.2/GenomeAnalysisTK.jar \
    -T IndelRealigner \
    - nt 10 \
    --consensusDeterminationModel KNOWNS_ONLY \
    -LOD 0.4 \
    -R $INDEXTDIR \
    -I $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.bam \
    --intervals $INTERVALS \
    -known $KNOWNSITES \
    -targetIntervals $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigner.intervals \
    -o $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.bam

echo "---------------------------------------"
echo 'BaseRecalibrator - create recal table' 

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS  -Xms3200m -Xmx3600m -jar /usr/local/GenomeAnalysisTK-3.2.2/GenomeAnalysisTK.jar \
    -T BaseRecalibrator \
    -nt 10 \
    -R $INDEXTDIR \
    -I $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.bam \
    --intervals $INTERVALS \
    -known $KNOWNSITES \
    -o $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.table

echo "---------------------------------------"
echo 'PrintReads - get recal reads' 

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS  -Xms3200m -Xmx3600m -jar /usr/local/GenomeAnalysisTK-3.2.2/GenomeAnalysisTK.jar  \
    -T PrintReads \
    - nt 10 \
    -R $INDEXTDIR \
    --intervals $INTERVALS \
    -I $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.bam
    -BQSR $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.table \
    -o $OUTDIR/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.bam

echo "---------------------------------------"
echo 'HaplotypeCaller' 

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /usr/local/GenomeAnalysisTK-3.2.2/GenomeAnalysisTK.jar \
    -T HaplotypeCaller \
    -ERC GVCF \
    --minPruning 3 \
    --maxNumHaplotypesInPopulation 200 \
    --variant_index_type LINEAR \
    --variant_index_parameter 128000 \
    -contamination 0.0 \
    -G Standard \
    -R $INDEXTDIR \
    --intervals $INTERVALS \
    -I SAMPLE.dupmarked.reheader.bam \
    -o SAMPLE.haplotypecaller.g.vcf.gz

echo "---------------------------------------"
echo 'Finished' 


