#!/bin/bash
#PBS -N ZIP
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=10
#PBS -l mem=40gb
#PBS -l walltime=06:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Change to working directory"
cd /home/jwestaway/pk_pipeline/ZB_100/pk_data

echo "---------------------------------------"
echo "Unzip"
unzip batch2.zip

echo "---------------------------------------"
echo "Finsihed!"